### ISSUE TITLE
VS2013 Build is Broken

### ISSUE THREAD

**Issue by wbic16** [Microsoft/GSL#159]
It appears that the README is wrong at the very least. While reviewing CI builds, I only see gcc and clang referenced. A list of commits and issues observed is given below.

Commit c5c8a25: last version that worked
Commit 831c692: produces 'noexcept' errors
Commit 2f25ace: lastest, still broken

Steps to reproduce:
1. Run `git reset --hard c5c8a25f34b1bb1cd0a418749cfd7b6095e48f67`
2. Compile; observe no errors or warnings.
3. Run `git reset --hard 831c6926df2dd17a691abf7d84137435ff172025`
4. Compile; observe "error C3646: 'noexcept' : unknown override specifier"
5. Run `git reset --hard 2f25ace31fe7bff78386aa55fd18371cf0d113d8`
6. Compile; observe "warning C4068: unknown pragma" and "error C2057: expected constant expression" errors in array_view.h.

Hope this helps, thanks!

**Comment by neilmacintosh** [comment]
@annagrin can you look into this please?

**Comment by subhamoyg** [comment]
Hi,

I tried VS2013 build on windows_x64 with cmake_3.2.3 but it failed to compile. Was not able to attach the build log, so pasting below. Sorry for the length of the build report.
===============================================================================
Microsoft (R) Build Engine version 12.0.21005.1
[Microsoft .NET Framework, version 4.0.30319.42000]
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 10/24/2015 5:06:49 PM.
Project "<local_machine>\GIT_Repository\GSL\build-x64\ALL_BUILD.vcxproj" on node 1 (default targets).
Project "<local_machine>\GIT_Repository\GSL\build-x64\ALL_BUILD.vcxproj" (1) is building "<local_machine>\GIT_Repository\GSL\build-x64\tests\unittest-cpp\TestUnitTest++.vcxproj" (2) on node 1 (default targets).
Project "<local_machine>\GIT_Repository\GSL\build-x64\tests\unittest-cpp\TestUnitTest++.vcxproj" (2) is building "<local_machine>\GIT_Repository\GSL\build-x64\tests\unittest-cpp\UnitTest++.vcxproj" (3) on node 1 (default targets).
Project "<local_machine>\GIT_Repository\GSL\build-x64\tests\unittest-cpp\UnitTest++.vcxproj" (3) is building "<local_machine>\GIT_Repository\GSL\build-x64\ZERO_CHECK.vcxproj" (4) on node 1 (default targets).
InitializeBuildStatus:
  Creating "Win32\Debug\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
CustomBuild:
  All outputs are up-to-date.
FinalizeBuildStatus:
  Deleting file "Win32\Debug\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild".
  Touching "Win32\Debug\ZERO_CHECK\ZERO_CHECK.tlog\ZERO_CHECK.lastbuildstate".
Done Building Project "<local_machine>\GIT_Repository\GSL\build-x64\ZERO_CHECK.vcxproj" (default targets).
InitializeBuildStatus:
  Creating "UnitTest++.dir\Debug\UnitTest++.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
CustomBuild:
  All outputs are up-to-date.
ClCompile:
  All outputs are up-to-date.
Lib:
  All outputs are up-to-date.
  UnitTest++.vcxproj -> <local_machine>\GIT_Repository\GSL\build-x64\tests\unittest-cpp\Debug\UnitTest++.lib
FinalizeBuildStatus:
  Deleting file "UnitTest++.dir\Debug\UnitTest++.tlog\unsuccessfulbuild".
  Touching "UnitTest++.dir\Debug\UnitTest++.tlog\UnitTest++.lastbuildstate".
Done Building Project "<local_machine>\GIT_Repository\GSL\build-x64\tests\unittest-cpp\UnitTest++.vcxproj" (default targets).
InitializeBuildStatus:
  Creating "TestUnitTest++.dir\Debug\TestUnitTest++.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
CustomBuild:
  All outputs are up-to-date.
ClCompile:
  All outputs are up-to-date.
Link:
  All outputs are up-to-date.
  TestUnitTest++.vcxproj -> <local_machine>\GIT_Repository\GSL\build-x64\tests\unittest-cpp\Debug\TestUnitTest++.exe
PostBuildEvent:
  Description: Running unit tests
  setlocal
  Debug\TestUnitTest++.exe
  if %errorlevel% neq 0 goto :cmEnd
  :cmEnd
  endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
  :cmErrorLevel
  exit /b %1
  :cmDone
  if %errorlevel% neq 0 goto :VCEnd
  :VCEnd
  Success: 228 tests passed.
  Test time: 0.21 seconds.
FinalizeBuildStatus:
  Deleting file "TestUnitTest++.dir\Debug\TestUnitTest++.tlog\unsuccessfulbuild".
  Touching "TestUnitTest++.dir\Debug\TestUnitTest++.tlog\TestUnitTest++.lastbuildstate".
Done Building Project "<local_machine>\GIT_Repository\GSL\build-x64\tests\unittest-cpp\TestUnitTest++.vcxproj" (default targets).
Project "<local_machine>\GIT_Repository\GSL\build-x64\ALL_BUILD.vcxproj" (1) is building "<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj" (5) on node 1 (default targets).
InitializeBuildStatus:
  Touching "array_view_tests.dir\Debug\array_view_tests.tlog\unsuccessfulbuild".
CustomBuild:
  All outputs are up-to-date.
ClCompile:
  C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\CL.exe /c /I"<local_machine>\GIT_Repository\GSL\build-x64" /I<local_machine>\GIT_Repository\GSL\tests\..\include /I"<local_machine>\GIT_Repository\GSL\tests\.\unittest-cpp" /I"C:\Program Files (x86)\Visual Leak Detector\include" /Zi /nologo /W3 /WX- /Od /Ob0 /Oy- /D WIN32 /D _WINDOWS /D _DEBUG /D GSL_THROWS_FOR_TESTING /D _SCL_SECURE_NO_WARNINGS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /GR /Fo"array_view_tests.dir\Debug\\" /Fd"array_view_tests.dir\Debug\vc120.pdb" /Gd /TP /analyze- /errorReport:queue <local_machine>\GIT_Repository\GSL\tests\array_view_tests.cpp
  array_view_tests.cpp
<local_machine>\GIT_Repository\GSL\include\array_view.h(75): error C2057: expected constant expression [<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj]
          <local_machine>\GIT_Repository\GSL\include\array_view.h(568) : see reference to class template instantiation 'gsl::details::SizeTypeTraits<SizeType>' being compiled
          with
          [
              SizeType=size_t
          ]
          <local_machine>\GIT_Repository\GSL\include\array_view.h(1056) : see reference to class template instantiation 'gsl::static_bounds<SizeType,-1>' being compiled
          with
          [
              SizeType=size_t
          ]
          <local_machine>\GIT_Repository\GSL\include\array_view.h(1337) : see reference to class template instantiation 'gsl::basic_array_view<int,gsl::static_bounds<SizeType,-1>>' being compiled
          with
          [
              SizeType=size_t
          ]
          <local_machine>\GIT_Repository\GSL\tests\array_view_tests.cpp(39) : see reference to class template instantiation 'gsl::array_view<T,-1,>' being compiled
          with
          [
              T=int
          ]
<local_machine>\GIT_Repository\GSL\include\array_view.h(568): error C2057: expected constant expression [<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj]
<local_machine>\GIT_Repository\GSL\include\array_view.h(286): error C2057: expected constant expression [<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj]
          <local_machine>\GIT_Repository\GSL\include\array_view.h(311) : see reference to class template instantiation 'gsl::details::StaticSizeHelperImpl<SizeType,1,2,-1>' being compiled
          with
          [
              SizeType=size_t
          ]
          <local_machine>\GIT_Repository\GSL\include\array_view.h(430) : see reference to class template instantiation 'gsl::details::StaticSizeHelper<SizeType,1,2>' being compiled
          with
          [
              SizeType=size_t
          ]
          <local_machine>\GIT_Repository\GSL\include\array_view.h(360) : see reference to class template instantiation 'gsl::details::BoundsRanges<SizeType,2>' being compiled
          with
          [
              SizeType=size_t
          ]
          <local_machine>\GIT_Repository\GSL\include\array_view.h(425) : see reference to class template instantiation 'gsl::details::BoundsRanges<SizeType,-1,2>' being compiled
          with
          [
              SizeType=size_t
          ]
          <local_machine>\GIT_Repository\GSL\include\array_view.h(570) : see reference to class template instantiation 'gsl::details::BoundsRanges<SizeType,4,-1,2>' being compiled
          with
          [
              SizeType=size_t
          ]
<local_machine>\GIT_Repository\GSL\include\array_view.h(431): error C2057: expected constant expression [<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj]
<local_machine>\GIT_Repository\GSL\include\array_view.h(235): warning C4520: 'gsl::index<2,unsigned int>' : multiple default constructors specified [<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj]
          <local_machine>\GIT_Repository\GSL\tests\array_view_tests.cpp(94) : see reference to class template instantiation 'gsl::index<2,unsigned int>' being compiled
<local_machine>\GIT_Repository\GSL\include\array_view.h(235): warning C4520: 'gsl::index<1,unsigned int>' : multiple default constructors specified [<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj]
          <local_machine>\GIT_Repository\GSL\tests\array_view_tests.cpp(94) : see reference to class template instantiation 'gsl::index<1,unsigned int>' being compiled
<local_machine>\GIT_Repository\GSL\include\array_view.h(235): warning C4520: 'gsl::index<3,unsigned int>' : multiple default constructors specified [<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj]
          <local_machine>\GIT_Repository\GSL\tests\array_view_tests.cpp(165) : see reference to class template instantiation 'gsl::index<3,unsigned int>' being compiled
<local_machine>\GIT_Repository\GSL\include\array_view.h(235): warning C4520: 'gsl::index<3,short>' : multiple default constructors specified [<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj]
          <local_machine>\GIT_Repository\GSL\tests\array_view_tests.cpp(850) : see reference to class template instantiation 'gsl::index<3,short>' being compiled
<local_machine>\GIT_Repository\GSL\tests\array_view_tests.cpp(850): error C2440: 'initializing' : cannot convert from 'gsl::index<3,unsigned int>' to 'gsl::index<3,short>' [<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj]
          No constructor could take the source type, or constructor overload resolution was ambiguous
<local_machine>\GIT_Repository\GSL\include\array_view.h(235): warning C4520: 'gsl::index<3,__int64>' : multiple default constructors specified [<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj]
          <local_machine>\GIT_Repository\GSL\tests\array_view_tests.cpp(854) : see reference to class template instantiation 'gsl::index<3,__int64>' being compiled
<local_machine>\GIT_Repository\GSL\tests\array_view_tests.cpp(854): error C2440: 'initializing' : cannot convert from 'gsl::index<3,unsigned int>' to 'gsl::index<3,__int64>' [<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj]
          No constructor could take the source type, or constructor overload resolution was ambiguous
<local_machine>\GIT_Repository\GSL\include\array_view.h(235): warning C4520: 'gsl::index<1,short>' : multiple default constructors specified [<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj]
          <local_machine>\GIT_Repository\GSL\tests\array_view_tests.cpp(889) : see reference to class template instantiation 'gsl::index<1,short>' being compiled
<local_machine>\GIT_Repository\GSL\tests\array_view_tests.cpp(889): error C2440: 'initializing' : cannot convert from 'gsl::index<1,unsigned int>' to 'gsl::index<1,short>' [<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj]
          No constructor could take the source type, or constructor overload resolution was ambiguous
<local_machine>\GIT_Repository\GSL\include\array_view.h(235): warning C4520: 'gsl::index<1,__int64>' : multiple default constructors specified [<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj]
          <local_machine>\GIT_Repository\GSL\tests\array_view_tests.cpp(893) : see reference to class template instantiation 'gsl::index<1,__int64>' being compiled
<local_machine>\GIT_Repository\GSL\tests\array_view_tests.cpp(893): error C2440: 'initializing' : cannot convert from 'gsl::index<1,short>' to 'gsl::index<1,__int64>' [<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj]
          No constructor could take the source type, or constructor overload resolution was ambiguous
<local_machine>\GIT_Repository\GSL\include\array_view.h(235): warning C4520: 'gsl::index<2,int>' : multiple default constructors specified [<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj]
          <local_machine>\GIT_Repository\GSL\tests\array_view_tests.cpp(1290) : see reference to class template instantiation 'gsl::index<2,int>' being compiled
<local_machine>\GIT_Repository\GSL\include\array_view.h(235): warning C4520: 'gsl::index<2,short>' : multiple default constructors specified [<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj]
          <local_machine>\GIT_Repository\GSL\tests\array_view_tests.cpp(1291) : see reference to class template instantiation 'gsl::index<2,short>' being compiled
<local_machine>\GIT_Repository\GSL\tests\array_view_tests.cpp(1291): error C2440: 'initializing' : cannot convert from 'initializer-list' to 'gsl::index<2,short>' [<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj]
          No constructor could take the source type, or constructor overload resolution was ambiguous
<local_machine>\GIT_Repository\GSL\tests\array_view_tests.cpp(1306): error C2440: 'initializing' : cannot convert from 'initializer-list' to 'gsl::index<2,unsigned int>' [<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj]
          No constructor could take the source type, or constructor overload resolution was ambiguous
<local_machine>\GIT_Repository\GSL\tests\array_view_tests.cpp(1315): error C2440: 'initializing' : cannot convert from 'initializer-list' to 'gsl::index<2,int>' [<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj]
          No constructor could take the source type, or constructor overload resolution was ambiguous
<local_machine>\GIT_Repository\GSL\include\array_view.h(235): warning C4520: 'gsl::index<2,unsigned short>' : multiple default constructors specified [<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj]
          <local_machine>\GIT_Repository\GSL\tests\array_view_tests.cpp(1324) : see reference to class template instantiation 'gsl::index<2,unsigned short>' being compiled
<local_machine>\GIT_Repository\GSL\tests\array_view_tests.cpp(1324): error C2440: 'initializing' : cannot convert from 'initializer-list' to 'gsl::index<2,unsigned short>' [<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj]
          No constructor could take the source type, or constructor overload resolution was ambiguous
<local_machine>\GIT_Repository\GSL\include\array_view.h(235): warning C4520: 'gsl::index<2,__int64>' : multiple default constructors specified [<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj]
          <local_machine>\GIT_Repository\GSL\tests\array_view_tests.cpp(1333) : see reference to class template instantiation 'gsl::index<2,__int64>' being compiled
<local_machine>\GIT_Repository\GSL\tests\array_view_tests.cpp(1333): error C2440: 'initializing' : cannot convert from 'initializer-list' to 'gsl::index<2,__int64>' [<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj]
          No constructor could take the source type, or constructor overload resolution was ambiguous
<local_machine>\GIT_Repository\GSL\tests\array_view_tests.cpp(1342): error C2440: 'initializing' : cannot convert from 'initializer-list' to 'gsl::index<2,__int64>' [<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj]
          No constructor could take the source type, or constructor overload resolution was ambiguous
<local_machine>\GIT_Repository\GSL\include\array_view.h(235): warning C4520: 'gsl::index<2,unsigned __int64>' : multiple default constructors specified [<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj]
          <local_machine>\GIT_Repository\GSL\tests\array_view_tests.cpp(1351) : see reference to class template instantiation 'gsl::index<2,unsigned __int64>' being compiled
<local_machine>\GIT_Repository\GSL\tests\array_view_tests.cpp(1351): error C2440: 'initializing' : cannot convert from 'initializer-list' to 'gsl::index<2,unsigned __int64>' [<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj]
          No constructor could take the source type, or constructor overload resolution was ambiguous
<local_machine>\GIT_Repository\GSL\include\array_view.h(235): warning C4520: 'gsl::index<1,int>' : multiple default constructors specified [<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj]
          <local_machine>\GIT_Repository\GSL\tests\array_view_tests.cpp(1363) : see reference to class template instantiation 'gsl::index<1,int>' being compiled
<local_machine>\GIT_Repository\GSL\tests\array_view_tests.cpp(1364): error C2440: 'initializing' : cannot convert from 'initializer-list' to 'gsl::index<1,short>' [<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj]
          No constructor could take the source type, or constructor overload resolution was ambiguous
<local_machine>\GIT_Repository\GSL\tests\array_view_tests.cpp(1379): error C2440: 'initializing' : cannot convert from 'initializer-list' to 'gsl::index<1,unsigned int>' [<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj]
          No constructor could take the source type, or constructor overload resolution was ambiguous
<local_machine>\GIT_Repository\GSL\tests\array_view_tests.cpp(1387): error C2440: 'initializing' : cannot convert from 'initializer-list' to 'gsl::index<1,int>' [<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj]
          No constructor could take the source type, or constructor overload resolution was ambiguous
<local_machine>\GIT_Repository\GSL\include\array_view.h(235): warning C4520: 'gsl::index<1,unsigned short>' : multiple default constructors specified [<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj]
          <local_machine>\GIT_Repository\GSL\tests\array_view_tests.cpp(1395) : see reference to class template instantiation 'gsl::index<1,unsigned short>' being compiled
<local_machine>\GIT_Repository\GSL\tests\array_view_tests.cpp(1395): error C2440: 'initializing' : cannot convert from 'initializer-list' to 'gsl::index<1,unsigned short>' [<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj]
          No constructor could take the source type, or constructor overload resolution was ambiguous
<local_machine>\GIT_Repository\GSL\tests\array_view_tests.cpp(1403): error C2440: 'initializing' : cannot convert from 'initializer-list' to 'gsl::index<1,__int64>' [<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj]
          No constructor could take the source type, or constructor overload resolution was ambiguous
<local_machine>\GIT_Repository\GSL\tests\array_view_tests.cpp(1411): error C2440: 'initializing' : cannot convert from 'initializer-list' to 'gsl::index<1,__int64>' [<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj]
          No constructor could take the source type, or constructor overload resolution was ambiguous
<local_machine>\GIT_Repository\GSL\include\array_view.h(235): warning C4520: 'gsl::index<1,unsigned __int64>' : multiple default constructors specified [<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj]
          <local_machine>\GIT_Repository\GSL\tests\array_view_tests.cpp(1419) : see reference to class template instantiation 'gsl::index<1,unsigned __int64>' being compiled
<local_machine>\GIT_Repository\GSL\tests\array_view_tests.cpp(1419): error C2440: 'initializing' : cannot convert from 'initializer-list' to 'gsl::index<1,unsigned __int64>' [<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj]
          No constructor could take the source type, or constructor overload resolution was ambiguous
<local_machine>\GIT_Repository\GSL\include\array_view.h(235): warning C4520: 'gsl::index<3,char>' : multiple default constructors specified [<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj]
          <local_machine>\GIT_Repository\GSL\tests\array_view_tests.cpp(1572) : see reference to class template instantiation 'gsl::index<3,char>' being compiled
<local_machine>\GIT_Repository\GSL\include\array_view.h(235): warning C4520: 'gsl::index<2,char>' : multiple default constructors specified [<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj]
          <local_machine>\GIT_Repository\GSL\tests\array_view_tests.cpp(1572) : see reference to class template instantiation 'gsl::index<2,char>' being compiled
<local_machine>\GIT_Repository\GSL\include\array_view.h(235): warning C4520: 'gsl::index<1,char>' : multiple default constructors specified [<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj]
          <local_machine>\GIT_Repository\GSL\tests\array_view_tests.cpp(1572) : see reference to class template instantiation 'gsl::index<1,char>' being compiled
Done Building Project "<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj" (default targets) -- FAILED.
Project "<local_machine>\GIT_Repository\GSL\build-x64\ALL_BUILD.vcxproj" (1) is building "<local_machine>\GIT_Repository\GSL\build-x64\tests\assertion_tests.vcxproj" (6) on node 1 (default targets).
InitializeBuildStatus:
  Touching "assertion_tests.dir\Debug\assertion_tests.tlog\unsuccessfulbuild".
CustomBuild:
  All outputs are up-to-date.
ClCompile:
  C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\CL.exe /c /I"<local_machine>\GIT_Repository\GSL\build-x64" /I<local_machine>\GIT_Repository\GSL\tests\..\include /I"<local_machine>\GIT_Repository\GSL\tests\.\unittest-cpp" /I"C:\Program Files (x86)\Visual Leak Detector\include" /Zi /nologo /W3 /WX- /Od /Ob0 /Oy- /D WIN32 /D _WINDOWS /D _DEBUG /D GSL_THROWS_FOR_TESTING /D _SCL_SECURE_NO_WARNINGS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /GR /Fo"assertion_tests.dir\Debug\\" /Fd"assertion_tests.dir\Debug\vc120.pdb" /Gd /TP /analyze- /errorReport:queue <local_machine>\GIT_Repository\GSL\tests\assertion_tests.cpp
  assertion_tests.cpp
<local_machine>\git_repository\gsl\include\array_view.h(75): error C2057: expected constant expression [<local_machine>\GIT_Repository\GSL\build-x64\tests\assertion_tests.vcxproj]
          <local_machine>\git_repository\gsl\include\array_view.h(568) : see reference to class template instantiation 'gsl::details::SizeTypeTraits<SizeType>' being compiled
          with
          [
              SizeType=gsl::details::ArrayViewTypeTraits<char,std::true_type>::size_type
          ]
          <local_machine>\git_repository\gsl\include\array_view.h(1056) : see reference to class template instantiation 'gsl::static_bounds<gsl::details::ArrayViewTypeTraits<ValueTypeOpt,std::true_type>::size_type,-1>' being compiled
          with
          [
              ValueTypeOpt=char
          ]
          <local_machine>\git_repository\gsl\include\array_view.h(1337) : see reference to class template instantiation 'gsl::basic_array_view<char,gsl::static_bounds<gsl::details::ArrayViewTypeTraits<ValueTypeOpt,std::true_type>::size_type,-1>>' being compiled
          with
          [
              ValueTypeOpt=char
          ]
          <local_machine>\git_repository\gsl\include\string_view.h(104) : see reference to class template instantiation 'gsl::array_view<CharT,-1,>' being compiled
          with
          [
              CharT=char
          ]
<local_machine>\git_repository\gsl\include\array_view.h(568): error C2057: expected constant expression [<local_machine>\GIT_Repository\GSL\build-x64\tests\assertion_tests.vcxproj]
Done Building Project "<local_machine>\GIT_Repository\GSL\build-x64\tests\assertion_tests.vcxproj" (default targets) -- FAILED.
Project "<local_machine>\GIT_Repository\GSL\build-x64\ALL_BUILD.vcxproj" (1) is building "<local_machine>\GIT_Repository\GSL\build-x64\tests\at_tests.vcxproj" (7) on node 1 (default targets).
InitializeBuildStatus:
  Touching "at_tests.dir\Debug\at_tests.tlog\unsuccessfulbuild".
CustomBuild:
  All outputs are up-to-date.
ClCompile:
  C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\CL.exe /c /I"<local_machine>\GIT_Repository\GSL\build-x64" /I<local_machine>\GIT_Repository\GSL\tests\..\include /I"<local_machine>\GIT_Repository\GSL\tests\.\unittest-cpp" /I"C:\Program Files (x86)\Visual Leak Detector\include" /Zi /nologo /W3 /WX- /Od /Ob0 /Oy- /D WIN32 /D _WINDOWS /D _DEBUG /D GSL_THROWS_FOR_TESTING /D _SCL_SECURE_NO_WARNINGS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /GR /Fo"at_tests.dir\Debug\\" /Fd"at_tests.dir\Debug\vc120.pdb" /Gd /TP /analyze- /errorReport:queue <local_machine>\GIT_Repository\GSL\tests\at_tests.cpp
  at_tests.cpp
<local_machine>\git_repository\gsl\include\array_view.h(75): error C2057: expected constant expression [<local_machine>\GIT_Repository\GSL\build-x64\tests\at_tests.vcxproj]
          <local_machine>\git_repository\gsl\include\array_view.h(568) : see reference to class template instantiation 'gsl::details::SizeTypeTraits<SizeType>' being compiled
          with
          [
              SizeType=gsl::details::ArrayViewTypeTraits<char,std::true_type>::size_type
          ]
          <local_machine>\git_repository\gsl\include\array_view.h(1056) : see reference to class template instantiation 'gsl::static_bounds<gsl::details::ArrayViewTypeTraits<ValueTypeOpt,std::true_type>::size_type,-1>' being compiled
          with
          [
              ValueTypeOpt=char
          ]
          <local_machine>\git_repository\gsl\include\array_view.h(1337) : see reference to class template instantiation 'gsl::basic_array_view<char,gsl::static_bounds<gsl::details::ArrayViewTypeTraits<ValueTypeOpt,std::true_type>::size_type,-1>>' being compiled
          with
          [
              ValueTypeOpt=char
          ]
          <local_machine>\git_repository\gsl\include\string_view.h(104) : see reference to class template instantiation 'gsl::array_view<CharT,-1,>' being compiled
          with
          [
              CharT=char
          ]
<local_machine>\git_repository\gsl\include\array_view.h(568): error C2057: expected constant expression [<local_machine>\GIT_Repository\GSL\build-x64\tests\at_tests.vcxproj]
Done Building Project "<local_machine>\GIT_Repository\GSL\build-x64\tests\at_tests.vcxproj" (default targets) -- FAILED.
Project "<local_machine>\GIT_Repository\GSL\build-x64\ALL_BUILD.vcxproj" (1) is building "<local_machine>\GIT_Repository\GSL\build-x64\tests\bounds_tests.vcxproj" (8) on node 1 (default targets).
InitializeBuildStatus:
  Touching "bounds_tests.dir\Debug\bounds_tests.tlog\unsuccessfulbuild".
CustomBuild:
  All outputs are up-to-date.
ClCompile:
  C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\CL.exe /c /I"<local_machine>\GIT_Repository\GSL\build-x64" /I<local_machine>\GIT_Repository\GSL\tests\..\include /I"<local_machine>\GIT_Repository\GSL\tests\.\unittest-cpp" /I"C:\Program Files (x86)\Visual Leak Detector\include" /Zi /nologo /W3 /WX- /Od /Ob0 /Oy- /D WIN32 /D _WINDOWS /D _DEBUG /D GSL_THROWS_FOR_TESTING /D _SCL_SECURE_NO_WARNINGS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /GR /Fo"bounds_tests.dir\Debug\\" /Fd"bounds_tests.dir\Debug\vc120.pdb" /Gd /TP /analyze- /errorReport:queue <local_machine>\GIT_Repository\GSL\tests\bounds_tests.cpp
  bounds_tests.cpp
<local_machine>\GIT_Repository\GSL\include\array_view.h(75): error C2057: expected constant expression [<local_machine>\GIT_Repository\GSL\build-x64\tests\bounds_tests.vcxproj]
          <local_machine>\GIT_Repository\GSL\include\array_view.h(568) : see reference to class template instantiation 'gsl::details::SizeTypeTraits<SizeType>' being compiled
          with
          [
              SizeType=unsigned int
          ]
          <local_machine>\GIT_Repository\GSL\tests\bounds_tests.cpp(33) : see reference to class template instantiation 'gsl::static_bounds<unsigned int,-1,3,4>' being compiled
<local_machine>\GIT_Repository\GSL\include\array_view.h(568): error C2057: expected constant expression [<local_machine>\GIT_Repository\GSL\build-x64\tests\bounds_tests.vcxproj]
<local_machine>\GIT_Repository\GSL\include\array_view.h(286): error C2057: expected constant expression [<local_machine>\GIT_Repository\GSL\build-x64\tests\bounds_tests.vcxproj]
          <local_machine>\GIT_Repository\GSL\include\array_view.h(311) : see reference to class template instantiation 'gsl::details::StaticSizeHelperImpl<SizeType,1,4,-1>' being compiled
          with
          [
              SizeType=unsigned int
          ]
          <local_machine>\GIT_Repository\GSL\include\array_view.h(430) : see reference to class template instantiation 'gsl::details::StaticSizeHelper<SizeType,1,4>' being compiled
          with
          [
              SizeType=unsigned int
          ]
          <local_machine>\GIT_Repository\GSL\include\array_view.h(425) : see reference to class template instantiation 'gsl::details::BoundsRanges<SizeType,4>' being compiled
          with
          [
              SizeType=unsigned int
          ]
          <local_machine>\GIT_Repository\GSL\include\array_view.h(360) : see reference to class template instantiation 'gsl::details::BoundsRanges<SizeType,3,4>' being compiled
          with
          [
              SizeType=unsigned int
          ]
          <local_machine>\GIT_Repository\GSL\include\array_view.h(570) : see reference to class template instantiation 'gsl::details::BoundsRanges<SizeType,-1,3,4>' being compiled
          with
          [
              SizeType=unsigned int
          ]
<local_machine>\GIT_Repository\GSL\include\array_view.h(431): error C2057: expected constant expression [<local_machine>\GIT_Repository\GSL\build-x64\tests\bounds_tests.vcxproj]
<local_machine>\GIT_Repository\GSL\include\array_view.h(235): warning C4520: 'gsl::index<3,unsigned int>' : multiple default constructors specified [<local_machine>\GIT_Repository\GSL\build-x64\tests\bounds_tests.vcxproj]
          <local_machine>\GIT_Repository\GSL\include\array_view.h(801) : see reference to class template instantiation 'gsl::index<3,unsigned int>' being compiled
          <local_machine>\GIT_Repository\GSL\tests\bounds_tests.cpp(33) : see reference to class template instantiation 'gsl::bounds_iterator<const gsl::index<3,unsigned int>>' being compiled
Done Building Project "<local_machine>\GIT_Repository\GSL\build-x64\tests\bounds_tests.vcxproj" (default targets) -- FAILED.
Project "<local_machine>\GIT_Repository\GSL\build-x64\ALL_BUILD.vcxproj" (1) is building "<local_machine>\GIT_Repository\GSL\build-x64\tests\notnull_tests.vcxproj" (9) on node 1 (default targets).
InitializeBuildStatus:
  Touching "notnull_tests.dir\Debug\notnull_tests.tlog\unsuccessfulbuild".
CustomBuild:
  All outputs are up-to-date.
ClCompile:
  C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\CL.exe /c /I"<local_machine>\GIT_Repository\GSL\build-x64" /I<local_machine>\GIT_Repository\GSL\tests\..\include /I"<local_machine>\GIT_Repository\GSL\tests\.\unittest-cpp" /I"C:\Program Files (x86)\Visual Leak Detector\include" /Zi /nologo /W3 /WX- /Od /Ob0 /Oy- /D WIN32 /D _WINDOWS /D _DEBUG /D GSL_THROWS_FOR_TESTING /D _SCL_SECURE_NO_WARNINGS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /GR /Fo"notnull_tests.dir\Debug\\" /Fd"notnull_tests.dir\Debug\vc120.pdb" /Gd /TP /analyze- /errorReport:queue <local_machine>\GIT_Repository\GSL\tests\notnull_tests.cpp
  notnull_tests.cpp
<local_machine>\git_repository\gsl\include\array_view.h(75): error C2057: expected constant expression [<local_machine>\GIT_Repository\GSL\build-x64\tests\notnull_tests.vcxproj]
          <local_machine>\git_repository\gsl\include\array_view.h(568) : see reference to class template instantiation 'gsl::details::SizeTypeTraits<SizeType>' being compiled
          with
          [
              SizeType=gsl::details::ArrayViewTypeTraits<char,std::true_type>::size_type
          ]
          <local_machine>\git_repository\gsl\include\array_view.h(1056) : see reference to class template instantiation 'gsl::static_bounds<gsl::details::ArrayViewTypeTraits<ValueTypeOpt,std::true_type>::size_type,-1>' being compiled
          with
          [
              ValueTypeOpt=char
          ]
          <local_machine>\git_repository\gsl\include\array_view.h(1337) : see reference to class template instantiation 'gsl::basic_array_view<char,gsl::static_bounds<gsl::details::ArrayViewTypeTraits<ValueTypeOpt,std::true_type>::size_type,-1>>' being compiled
          with
          [
              ValueTypeOpt=char
          ]
          <local_machine>\git_repository\gsl\include\string_view.h(104) : see reference to class template instantiation 'gsl::array_view<CharT,-1,>' being compiled
          with
          [
              CharT=char
          ]
<local_machine>\git_repository\gsl\include\array_view.h(568): error C2057: expected constant expression [<local_machine>\GIT_Repository\GSL\build-x64\tests\notnull_tests.vcxproj]
Done Building Project "<local_machine>\GIT_Repository\GSL\build-x64\tests\notnull_tests.vcxproj" (default targets) -- FAILED.
Project "<local_machine>\GIT_Repository\GSL\build-x64\ALL_BUILD.vcxproj" (1) is building "<local_machine>\GIT_Repository\GSL\build-x64\tests\owner_tests.vcxproj" (10) on node 1 (default targets).
InitializeBuildStatus:
  Touching "owner_tests.dir\Debug\owner_tests.tlog\unsuccessfulbuild".
CustomBuild:
  All outputs are up-to-date.
ClCompile:
  C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\CL.exe /c /I"<local_machine>\GIT_Repository\GSL\build-x64" /I<local_machine>\GIT_Repository\GSL\tests\..\include /I"<local_machine>\GIT_Repository\GSL\tests\.\unittest-cpp" /I"C:\Program Files (x86)\Visual Leak Detector\include" /Zi /nologo /W3 /WX- /Od /Ob0 /Oy- /D WIN32 /D _WINDOWS /D _DEBUG /D GSL_THROWS_FOR_TESTING /D _SCL_SECURE_NO_WARNINGS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /GR /Fo"owner_tests.dir\Debug\\" /Fd"owner_tests.dir\Debug\vc120.pdb" /Gd /TP /analyze- /errorReport:queue <local_machine>\GIT_Repository\GSL\tests\owner_tests.cpp
  owner_tests.cpp
<local_machine>\git_repository\gsl\include\array_view.h(75): error C2057: expected constant expression [<local_machine>\GIT_Repository\GSL\build-x64\tests\owner_tests.vcxproj]
          <local_machine>\git_repository\gsl\include\array_view.h(568) : see reference to class template instantiation 'gsl::details::SizeTypeTraits<SizeType>' being compiled
          with
          [
              SizeType=gsl::details::ArrayViewTypeTraits<char,std::true_type>::size_type
          ]
          <local_machine>\git_repository\gsl\include\array_view.h(1056) : see reference to class template instantiation 'gsl::static_bounds<gsl::details::ArrayViewTypeTraits<ValueTypeOpt,std::true_type>::size_type,-1>' being compiled
          with
          [
              ValueTypeOpt=char
          ]
          <local_machine>\git_repository\gsl\include\array_view.h(1337) : see reference to class template instantiation 'gsl::basic_array_view<char,gsl::static_bounds<gsl::details::ArrayViewTypeTraits<ValueTypeOpt,std::true_type>::size_type,-1>>' being compiled
          with
          [
              ValueTypeOpt=char
          ]
          <local_machine>\git_repository\gsl\include\string_view.h(104) : see reference to class template instantiation 'gsl::array_view<CharT,-1,>' being compiled
          with
          [
              CharT=char
          ]
<local_machine>\git_repository\gsl\include\array_view.h(568): error C2057: expected constant expression [<local_machine>\GIT_Repository\GSL\build-x64\tests\owner_tests.vcxproj]
Done Building Project "<local_machine>\GIT_Repository\GSL\build-x64\tests\owner_tests.vcxproj" (default targets) -- FAILED.
Project "<local_machine>\GIT_Repository\GSL\build-x64\ALL_BUILD.vcxproj" (1) is building "<local_machine>\GIT_Repository\GSL\build-x64\tests\string_view_tests.vcxproj" (11) on node 1 (default targets).
InitializeBuildStatus:
  Touching "string_view_tests.dir\Debug\string_v.8429896A.tlog\unsuccessfulbuild".
CustomBuild:
  All outputs are up-to-date.
ClCompile:
  C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\CL.exe /c /I"<local_machine>\GIT_Repository\GSL\build-x64" /I<local_machine>\GIT_Repository\GSL\tests\..\include /I"<local_machine>\GIT_Repository\GSL\tests\.\unittest-cpp" /I"C:\Program Files (x86)\Visual Leak Detector\include" /Zi /nologo /W3 /WX- /Od /Ob0 /Oy- /D WIN32 /D _WINDOWS /D _DEBUG /D GSL_THROWS_FOR_TESTING /D _SCL_SECURE_NO_WARNINGS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /GR /Fo"string_view_tests.dir\Debug\\" /Fd"string_view_tests.dir\Debug\vc120.pdb" /Gd /TP /analyze- /errorReport:queue <local_machine>\GIT_Repository\GSL\tests\string_view_tests.cpp
  string_view_tests.cpp
<local_machine>\git_repository\gsl\include\array_view.h(75): error C2057: expected constant expression [<local_machine>\GIT_Repository\GSL\build-x64\tests\string_view_tests.vcxproj]
          <local_machine>\git_repository\gsl\include\array_view.h(568) : see reference to class template instantiation 'gsl::details::SizeTypeTraits<SizeType>' being compiled
          with
          [
              SizeType=gsl::details::ArrayViewTypeTraits<char,std::true_type>::size_type
          ]
          <local_machine>\git_repository\gsl\include\array_view.h(1056) : see reference to class template instantiation 'gsl::static_bounds<gsl::details::ArrayViewTypeTraits<ValueTypeOpt,std::true_type>::size_type,-1>' being compiled
          with
          [
              ValueTypeOpt=char
          ]
          <local_machine>\git_repository\gsl\include\array_view.h(1337) : see reference to class template instantiation 'gsl::basic_array_view<char,gsl::static_bounds<gsl::details::ArrayViewTypeTraits<ValueTypeOpt,std::true_type>::size_type,-1>>' being compiled
          with
          [
              ValueTypeOpt=char
          ]
          <local_machine>\GIT_Repository\GSL\include\string_view.h(104) : see reference to class template instantiation 'gsl::array_view<CharT,-1,>' being compiled
          with
          [
              CharT=char
          ]
<local_machine>\git_repository\gsl\include\array_view.h(568): error C2057: expected constant expression [<local_machine>\GIT_Repository\GSL\build-x64\tests\string_view_tests.vcxproj]
Done Building Project "<local_machine>\GIT_Repository\GSL\build-x64\tests\string_view_tests.vcxproj" (default targets) -- FAILED.
Project "<local_machine>\GIT_Repository\GSL\build-x64\ALL_BUILD.vcxproj" (1) is building "<local_machine>\GIT_Repository\GSL\build-x64\tests\utils_tests.vcxproj" (12) on node 1 (default targets).
InitializeBuildStatus:
  Touching "utils_tests.dir\Debug\utils_tests.tlog\unsuccessfulbuild".
CustomBuild:
  All outputs are up-to-date.
ClCompile:
  C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\CL.exe /c /I"<local_machine>\GIT_Repository\GSL\build-x64" /I<local_machine>\GIT_Repository\GSL\tests\..\include /I"<local_machine>\GIT_Repository\GSL\tests\.\unittest-cpp" /I"C:\Program Files (x86)\Visual Leak Detector\include" /Zi /nologo /W3 /WX- /Od /Ob0 /Oy- /D WIN32 /D _WINDOWS /D _DEBUG /D GSL_THROWS_FOR_TESTING /D _SCL_SECURE_NO_WARNINGS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /GR /Fo"utils_tests.dir\Debug\\" /Fd"utils_tests.dir\Debug\vc120.pdb" /Gd /TP /analyze- /errorReport:queue <local_machine>\GIT_Repository\GSL\tests\utils_tests.cpp
  utils_tests.cpp
<local_machine>\git_repository\gsl\include\array_view.h(75): error C2057: expected constant expression [<local_machine>\GIT_Repository\GSL\build-x64\tests\utils_tests.vcxproj]
          <local_machine>\git_repository\gsl\include\array_view.h(568) : see reference to class template instantiation 'gsl::details::SizeTypeTraits<SizeType>' being compiled
          with
          [
              SizeType=gsl::details::ArrayViewTypeTraits<char,std::true_type>::size_type
          ]
          <local_machine>\git_repository\gsl\include\array_view.h(1056) : see reference to class template instantiation 'gsl::static_bounds<gsl::details::ArrayViewTypeTraits<ValueTypeOpt,std::true_type>::size_type,-1>' being compiled
          with
          [
              ValueTypeOpt=char
          ]
          <local_machine>\git_repository\gsl\include\array_view.h(1337) : see reference to class template instantiation 'gsl::basic_array_view<char,gsl::static_bounds<gsl::details::ArrayViewTypeTraits<ValueTypeOpt,std::true_type>::size_type,-1>>' being compiled
          with
          [
              ValueTypeOpt=char
          ]
          <local_machine>\git_repository\gsl\include\string_view.h(104) : see reference to class template instantiation 'gsl::array_view<CharT,-1,>' being compiled
          with
          [
              CharT=char
          ]
<local_machine>\git_repository\gsl\include\array_view.h(568): error C2057: expected constant expression [<local_machine>\GIT_Repository\GSL\build-x64\tests\utils_tests.vcxproj]
Done Building Project "<local_machine>\GIT_Repository\GSL\build-x64\tests\utils_tests.vcxproj" (default targets) -- FAILED.
Done Building Project "<local_machine>\GIT_Repository\GSL\build-x64\ALL_BUILD.vcxproj" (default targets) -- FAILED.

Build FAILED.

"<local_machine>\GIT_Repository\GSL\build-x64\ALL_BUILD.vcxproj" (default target) (1) ->
"<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj" (default target) (5) ->
(ClCompile target) -> 
  <local_machine>\GIT_Repository\GSL\include\array_view.h(235): warning C4520: 'gsl::index<2,unsigned int>' : multiple default constructors specified [<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj]
  <local_machine>\GIT_Repository\GSL\include\array_view.h(235): warning C4520: 'gsl::index<1,unsigned int>' : multiple default constructors specified [<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj]
  <local_machine>\GIT_Repository\GSL\include\array_view.h(235): warning C4520: 'gsl::index<3,unsigned int>' : multiple default constructors specified [<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj]
  <local_machine>\GIT_Repository\GSL\include\array_view.h(235): warning C4520: 'gsl::index<3,short>' : multiple default constructors specified [<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj]
  <local_machine>\GIT_Repository\GSL\include\array_view.h(235): warning C4520: 'gsl::index<3,__int64>' : multiple default constructors specified [<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj]
  <local_machine>\GIT_Repository\GSL\include\array_view.h(235): warning C4520: 'gsl::index<1,short>' : multiple default constructors specified [<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj]
  <local_machine>\GIT_Repository\GSL\include\array_view.h(235): warning C4520: 'gsl::index<1,__int64>' : multiple default constructors specified [<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj]
  <local_machine>\GIT_Repository\GSL\include\array_view.h(235): warning C4520: 'gsl::index<2,int>' : multiple default constructors specified [<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj]
  <local_machine>\GIT_Repository\GSL\include\array_view.h(235): warning C4520: 'gsl::index<2,short>' : multiple default constructors specified [<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj]
  <local_machine>\GIT_Repository\GSL\include\array_view.h(235): warning C4520: 'gsl::index<2,unsigned short>' : multiple default constructors specified [<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj]
  <local_machine>\GIT_Repository\GSL\include\array_view.h(235): warning C4520: 'gsl::index<2,__int64>' : multiple default constructors specified [<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj]
  <local_machine>\GIT_Repository\GSL\include\array_view.h(235): warning C4520: 'gsl::index<2,unsigned __int64>' : multiple default constructors specified [<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj]
  <local_machine>\GIT_Repository\GSL\include\array_view.h(235): warning C4520: 'gsl::index<1,int>' : multiple default constructors specified [<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj]
  <local_machine>\GIT_Repository\GSL\include\array_view.h(235): warning C4520: 'gsl::index<1,unsigned short>' : multiple default constructors specified [<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj]
  <local_machine>\GIT_Repository\GSL\include\array_view.h(235): warning C4520: 'gsl::index<1,unsigned __int64>' : multiple default constructors specified [<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj]
  <local_machine>\GIT_Repository\GSL\include\array_view.h(235): warning C4520: 'gsl::index<3,char>' : multiple default constructors specified [<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj]
  <local_machine>\GIT_Repository\GSL\include\array_view.h(235): warning C4520: 'gsl::index<2,char>' : multiple default constructors specified [<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj]
  <local_machine>\GIT_Repository\GSL\include\array_view.h(235): warning C4520: 'gsl::index<1,char>' : multiple default constructors specified [<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj]


"<local_machine>\GIT_Repository\GSL\build-x64\ALL_BUILD.vcxproj" (default target) (1) ->
"<local_machine>\GIT_Repository\GSL\build-x64\tests\bounds_tests.vcxproj" (default target) (8) ->
  <local_machine>\GIT_Repository\GSL\include\array_view.h(235): warning C4520: 'gsl::index<3,unsigned int>' : multiple default constructors specified [<local_machine>\GIT_Repository\GSL\build-x64\tests\bounds_tests.vcxproj]


"<local_machine>\GIT_Repository\GSL\build-x64\ALL_BUILD.vcxproj" (default target) (1) ->
"<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj" (default target) (5) ->
(ClCompile target) -> 
  <local_machine>\GIT_Repository\GSL\include\array_view.h(75): error C2057: expected constant expression [<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj]
  <local_machine>\GIT_Repository\GSL\include\array_view.h(568): error C2057: expected constant expression [<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj]
  <local_machine>\GIT_Repository\GSL\include\array_view.h(286): error C2057: expected constant expression [<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj]
  <local_machine>\GIT_Repository\GSL\include\array_view.h(431): error C2057: expected constant expression [<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj]
  <local_machine>\GIT_Repository\GSL\tests\array_view_tests.cpp(850): error C2440: 'initializing' : cannot convert from 'gsl::index<3,unsigned int>' to 'gsl::index<3,short>' [<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj]
  <local_machine>\GIT_Repository\GSL\tests\array_view_tests.cpp(854): error C2440: 'initializing' : cannot convert from 'gsl::index<3,unsigned int>' to 'gsl::index<3,__int64>' [<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj]
  <local_machine>\GIT_Repository\GSL\tests\array_view_tests.cpp(889): error C2440: 'initializing' : cannot convert from 'gsl::index<1,unsigned int>' to 'gsl::index<1,short>' [<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj]
  <local_machine>\GIT_Repository\GSL\tests\array_view_tests.cpp(893): error C2440: 'initializing' : cannot convert from 'gsl::index<1,short>' to 'gsl::index<1,__int64>' [<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj]
  <local_machine>\GIT_Repository\GSL\tests\array_view_tests.cpp(1291): error C2440: 'initializing' : cannot convert from 'initializer-list' to 'gsl::index<2,short>' [<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj]
  <local_machine>\GIT_Repository\GSL\tests\array_view_tests.cpp(1306): error C2440: 'initializing' : cannot convert from 'initializer-list' to 'gsl::index<2,unsigned int>' [<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj]
  <local_machine>\GIT_Repository\GSL\tests\array_view_tests.cpp(1315): error C2440: 'initializing' : cannot convert from 'initializer-list' to 'gsl::index<2,int>' [<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj]
  <local_machine>\GIT_Repository\GSL\tests\array_view_tests.cpp(1324): error C2440: 'initializing' : cannot convert from 'initializer-list' to 'gsl::index<2,unsigned short>' [<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj]
  <local_machine>\GIT_Repository\GSL\tests\array_view_tests.cpp(1333): error C2440: 'initializing' : cannot convert from 'initializer-list' to 'gsl::index<2,__int64>' [<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj]
  <local_machine>\GIT_Repository\GSL\tests\array_view_tests.cpp(1342): error C2440: 'initializing' : cannot convert from 'initializer-list' to 'gsl::index<2,__int64>' [<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj]
  <local_machine>\GIT_Repository\GSL\tests\array_view_tests.cpp(1351): error C2440: 'initializing' : cannot convert from 'initializer-list' to 'gsl::index<2,unsigned __int64>' [<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj]
  <local_machine>\GIT_Repository\GSL\tests\array_view_tests.cpp(1364): error C2440: 'initializing' : cannot convert from 'initializer-list' to 'gsl::index<1,short>' [<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj]
  <local_machine>\GIT_Repository\GSL\tests\array_view_tests.cpp(1379): error C2440: 'initializing' : cannot convert from 'initializer-list' to 'gsl::index<1,unsigned int>' [<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj]
  <local_machine>\GIT_Repository\GSL\tests\array_view_tests.cpp(1387): error C2440: 'initializing' : cannot convert from 'initializer-list' to 'gsl::index<1,int>' [<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj]
  <local_machine>\GIT_Repository\GSL\tests\array_view_tests.cpp(1395): error C2440: 'initializing' : cannot convert from 'initializer-list' to 'gsl::index<1,unsigned short>' [<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj]
  <local_machine>\GIT_Repository\GSL\tests\array_view_tests.cpp(1403): error C2440: 'initializing' : cannot convert from 'initializer-list' to 'gsl::index<1,__int64>' [<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj]
  <local_machine>\GIT_Repository\GSL\tests\array_view_tests.cpp(1411): error C2440: 'initializing' : cannot convert from 'initializer-list' to 'gsl::index<1,__int64>' [<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj]
  <local_machine>\GIT_Repository\GSL\tests\array_view_tests.cpp(1419): error C2440: 'initializing' : cannot convert from 'initializer-list' to 'gsl::index<1,unsigned __int64>' [<local_machine>\GIT_Repository\GSL\build-x64\tests\array_view_tests.vcxproj]


"<local_machine>\GIT_Repository\GSL\build-x64\ALL_BUILD.vcxproj" (default target) (1) ->
"<local_machine>\GIT_Repository\GSL\build-x64\tests\assertion_tests.vcxproj" (default target) (6) ->
  <local_machine>\git_repository\gsl\include\array_view.h(75): error C2057: expected constant expression [<local_machine>\GIT_Repository\GSL\build-x64\tests\assertion_tests.vcxproj]
  <local_machine>\git_repository\gsl\include\array_view.h(568): error C2057: expected constant expression [<local_machine>\GIT_Repository\GSL\build-x64\tests\assertion_tests.vcxproj]


"<local_machine>\GIT_Repository\GSL\build-x64\ALL_BUILD.vcxproj" (default target) (1) ->
"<local_machine>\GIT_Repository\GSL\build-x64\tests\at_tests.vcxproj" (default target) (7) ->
  <local_machine>\git_repository\gsl\include\array_view.h(75): error C2057: expected constant expression [<local_machine>\GIT_Repository\GSL\build-x64\tests\at_tests.vcxproj]
  <local_machine>\git_repository\gsl\include\array_view.h(568): error C2057: expected constant expression [<local_machine>\GIT_Repository\GSL\build-x64\tests\at_tests.vcxproj]


"<local_machine>\GIT_Repository\GSL\build-x64\ALL_BUILD.vcxproj" (default target) (1) ->
"<local_machine>\GIT_Repository\GSL\build-x64\tests\bounds_tests.vcxproj" (default target) (8) ->
  <local_machine>\GIT_Repository\GSL\include\array_view.h(75): error C2057: expected constant expression [<local_machine>\GIT_Repository\GSL\build-x64\tests\bounds_tests.vcxproj]
  <local_machine>\GIT_Repository\GSL\include\array_view.h(568): error C2057: expected constant expression [<local_machine>\GIT_Repository\GSL\build-x64\tests\bounds_tests.vcxproj]
  <local_machine>\GIT_Repository\GSL\include\array_view.h(286): error C2057: expected constant expression [<local_machine>\GIT_Repository\GSL\build-x64\tests\bounds_tests.vcxproj]
  <local_machine>\GIT_Repository\GSL\include\array_view.h(431): error C2057: expected constant expression [<local_machine>\GIT_Repository\GSL\build-x64\tests\bounds_tests.vcxproj]


"<local_machine>\GIT_Repository\GSL\build-x64\ALL_BUILD.vcxproj" (default target) (1) ->
"<local_machine>\GIT_Repository\GSL\build-x64\tests\notnull_tests.vcxproj" (default target) (9) ->
  <local_machine>\git_repository\gsl\include\array_view.h(75): error C2057: expected constant expression [<local_machine>\GIT_Repository\GSL\build-x64\tests\notnull_tests.vcxproj]
  <local_machine>\git_repository\gsl\include\array_view.h(568): error C2057: expected constant expression [<local_machine>\GIT_Repository\GSL\build-x64\tests\notnull_tests.vcxproj]


"<local_machine>\GIT_Repository\GSL\build-x64\ALL_BUILD.vcxproj" (default target) (1) ->
"<local_machine>\GIT_Repository\GSL\build-x64\tests\owner_tests.vcxproj" (default target) (10) ->
  <local_machine>\git_repository\gsl\include\array_view.h(75): error C2057: expected constant expression [<local_machine>\GIT_Repository\GSL\build-x64\tests\owner_tests.vcxproj]
  <local_machine>\git_repository\gsl\include\array_view.h(568): error C2057: expected constant expression [<local_machine>\GIT_Repository\GSL\build-x64\tests\owner_tests.vcxproj]


"<local_machine>\GIT_Repository\GSL\build-x64\ALL_BUILD.vcxproj" (default target) (1) ->
"<local_machine>\GIT_Repository\GSL\build-x64\tests\string_view_tests.vcxproj" (default target) (11) ->
  <local_machine>\git_repository\gsl\include\array_view.h(75): error C2057: expected constant expression [<local_machine>\GIT_Repository\GSL\build-x64\tests\string_view_tests.vcxproj]
  <local_machine>\git_repository\gsl\include\array_view.h(568): error C2057: expected constant expression [<local_machine>\GIT_Repository\GSL\build-x64\tests\string_view_tests.vcxproj]


"<local_machine>\GIT_Repository\GSL\build-x64\ALL_BUILD.vcxproj" (default target) (1) ->
"<local_machine>\GIT_Repository\GSL\build-x64\tests\utils_tests.vcxproj" (default target) (12) ->
  <local_machine>\git_repository\gsl\include\array_view.h(75): error C2057: expected constant expression [<local_machine>\GIT_Repository\GSL\build-x64\tests\utils_tests.vcxproj]
  <local_machine>\git_repository\gsl\include\array_view.h(568): error C2057: expected constant expression [<local_machine>\GIT_Repository\GSL\build-x64\tests\utils_tests.vcxproj]

    19 Warning(s)
    38 Error(s)

Time Elapsed 00:00:05.08

===============================================================================

**Comment by rkhlebnikov** [comment]
In addition, `gsl::to_string` causes an internal compiler error for me in VS2013 Professional Update 5.

The simple code as `gsl::to_string(gsl::cstring_view<>{});` leads to:

> 1>c:\users\rk13\documents\visual studio 2013\projects\consoleapplication4\consoleapplication4\consoleapplication4.cpp(11): fatal error C1001: An internal error has occurred in the compiler.
1>  (compiler file 'f:\dd\vctools\compiler\cxxfe\sl\p1\cxx\dymto.c', line 10762)

**Comment by neilmacintosh** [comment]
@wbic16, @subhamoyg your issues should be resolved with the latest commits. Thanks for the reports!

**Comment by wbic16** [comment]
Woot! I'll give it a whirl tomorrow.

**Comment by rkhlebnikov** [comment]
The crash internal compiler error still happens for me. Can you reproduce the issue?

**Comment by neilmacintosh** [comment]
@rkhlebnikov I can! (which is why I didn't tag you in the last reply :-) ). I'm still digging into this to see if I can come up with a workaround for MSVC 2013. Meanwhile, I've logged the bug against our compiler.

**Comment by rkhlebnikov** [comment]
@neilmacintosh I thought you might be interested in a question I just posted at SO. http://stackoverflow.com/questions/33535221/boostany-rangegslstring-span-crash-in-release-mode
I'm not sure whether it deserves a separate issue (especially given that I'm not sure that it's the `string_span` problem), thus posting it here.

**Comment by neilmacintosh** [comment]
@rkhlebnikov thanks for the link. I took a look at your post, and have taken a stab at a possible answer over on SO.

**Comment by neilmacintosh** [comment]
@rkhlebnikov I just committed #169 which should workaround the compiler bug you were hitting with to_string(). Thanks for the report!

I think everything reported here has now been addressed, so I'm going to close out the issue. If I've missed something, please let me know. If there are new problems, feel free to open new issues.
