### ISSUE TITLE
Broken links in README.md

### ISSUE THREAD

**Issue by igetgames** [Microsoft/GSL#19]
The links provided in README.md to https://github.com/Microsoft/CppCoreGuidelines and [Standard C++ Foundation](https://github.com/Microsoft/GSL/blob/master/isocpp.org) (https://github.com/Microsoft/GSL/blob/master/isocpp.org) does not resolve. I couldn't find a repository named CppCoreGuidelines under the Microsoft organization (maybe it's private).

**Comment by gdr-at-ms** [comment]
Fixed by #20

**Comment by mvpete** [comment]
I think this link is still broken or private. https://github.com/Microsoft/CppCoreGuidelines

**Comment by neilmacintosh** [comment]
I think it might be broken because we haven't forked off the Microsoft guidelines yet. Andrew?
