### ISSUE TITLE
not_null<T*> and conversion from T&

### ISSUE THREAD

**Issue by NicolBolas** [microsoft/GSL#396]
There is a comment in `gsl.h` about `not_null` that says:

```
// If T is a pointer (i.e. T == U*) then
// - allow construction from U* or U&
```

This is not true, in several ways.

First, if you have `not_null<Foo*>` (where `Foo` is a class), you cannot construct `not_null<Foo*>` from an lvalue expression of type `Foo`. You _have_ to pass in a pointer.

Second, if you have `not_null<int*>`, trying to pass an `int` will catch the private deleted method. This is true for any type which is implicitly convertible to `int`.

There are two options to correct this:
1. Remove the erroneous comment.
2. Make the comment actually correct. This would almost certainly require a specialization for `not_null<T*>`, and possibly one for `not_null<int*>` as well.

I prefer option 2 here, because it allows a special optimization. If the user passes in a `T&`, then `not_null` should _not_ check to see if it is a NULL reference. After all, if it is, the user has already invoked UB. So if the user passes `T&`, it should just store a pointer with no checking. The idea here being that it is more optimal if you have a, for example, `vector<T>`, and you want to pass each element to a function that takes `not_null<T*>`. By having the `T&` overload, you can make sure that the compiler isn't doing a pointless check.

Of course, the constructor ought to be `explicit`, to avoid making `not_null` implicitly convertible from lvalues.

**Comment by neilmacintosh** [comment]
@NicolBolas I like option 2 as well.

**Comment by tiagomacarios** [comment]
@neilmacintosh Looks like this is outdated. Maybe we should close this one?

**Comment by NicolBolas** [comment]
I'm not sure what changed with `not_null` that would make this "outdated", but the current version of `not_null` still doesn't have a constructor that takes references if `T` is a pointer.

**Comment by tiagomacarios** [comment]
Yes you are correct, I guess my point was that the code does not make that promise anymore. Or at least I could not find that comment. But yes we should probably fix it.

**Comment by JordanMaples** [comment]
Maintainers' call: Sorry for the delay. This issue should have been closed as resolved with a previous fix. Thanks!

**Comment by Amaroker** [comment]
@JordanMaples

As far as I can see, the only change was that the comment now reflects the current code, but shouldn't the issue be fixed properly?

The issue remains as it's still not possible to efficiently convert from a reference. One of C++'s principles is that you shouldn't pay for what you don't need. Furthermore, it could be noexcept!

Is there a reluctance to add it to because of the explicit constructor? If so, would you consider adding it to strict_not_null? It already has explicit constructors.

**Comment by NicolBolas** [comment]
@JordanMaples 

> This issue should have been closed as resolved with a previous fix.

But... nothing was fixed. `not_null<T*>` does not have a constructor that takes a `T&` and does not do a NULL check. If you don't want to add such a constructor, then OK. But at least close it as "not desired", not "resolved with a previous fix" when the problem as stated wasn't actually resolved.

**Comment by Amaroker** [comment]
@JordanMaples 

Gentle reminder. Is there no desire to address this issue? If so, what's the motivation?

**Comment by hsutter** [comment]
We went back to try to clean up a bunch of `not_null` related issues, many of which had already been fixed with later commits, or we felt were otherwise addressed. It's possible we got this wrong, but AFAICT removing the comment does address this, doesn't it? (It's option 1 in the original request.)

That said, if someone wanted to reopen this, I would suggest opening a new issue and showing what the intended caller-side code is meant to look like, because it doesn't seem like there's enough information above to know what calling code was intended.

For example, given a function today that looks like this without `not_null`:

~~~
void f(X* p) {
    use(*p); // unconditional deref
}
~~~

and which today is invoked using 

~~~
X x;
f(&x);
~~~

the intention of `not_null` is to let the author of `f` rewrite this as way we encourage

~~~
void f(not_null<X*> p) {
    use(*p);
}
~~~

which does not change the calling code, it is still

~~~
X x;
f(&x);  // as before, even though f uses not_null
~~~

Note that this does not have the problem that the original # 2 suggestion cited, there is no extra null check here.

It sounds like the intention of this Issue is to allow the following to work:

~~~
X x;
f(x);  // <-- ?? note, "x" not "&x"
~~~

1) Is that what's being asked for? If so, how does this eliminate an extra null check?

2) Doesn't this lead to confusion, and changing/breaking existing call sites? This would change the meaning of every API that used a `not_null` parameter to let it accept arguments with a different level of indirection than today. That's a pretty fundamental change in usage (and likely not mentioned in any of the API's existing documentation), and it would seem to inject new ambiguities that were not allowed before. For example, what if there was an overload:

~~~
void f(not_null<X*>);
void f(Y); // + this overload, and say there is an implicit conversion from X to Y
~~~

so that an existing call site like this would invoke `f(Y)` via conversion:

~~~
X x;
f(x); // used to call f(Y) by converting x to Y
~~~

If we changed `not_null` so that `f(not_null<X*>)` is now a viable candidate for the call `f(x)`, aren't we injecting an ambiguity that makes this a compile time error (if `x` is non-const) and actually could select the other overload (e.g., calling `f(not_null<const X>)` with a const `X` object... https://godbolt.org/z/dsqM6K) which could silently change the meaning of existing code?

So I'm nervous about overloading on `T&` which changes the level of indirection at call sites, if I'm understanding the request correctly.

**Disclaimer:** I could well be making a thinko here and/or missing the point! That's why I think we need an example... so if you want to reopen this, could you please create a new Issue showing the code you want to work, and why it can/can't be written today? Thanks!

**Comment by Amaroker** [comment]
Thanks for the feedback. I've created a new issue with example.
